name: C++ CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lab: [lab1, lab2, lab3] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name:  Install googletest
      uses: cvpkg/googletest-action@v0.1
      with:
          googletest_tag: 'release-1.11.0'

    - name: Install dependencies
      run: |
        sudo apt-get clean
        sudo apt-get update
        sudo apt-get install -y \
        cmake \
        && sudo rm -rf /var/lib/apt/lists/*

    - name: Build Project
      run: |
        make build
        
    - name: Run Tests
      run: |
        cd build/${{ matrix.lab }}
        ./tests_${{ matrix.lab }}
